### ISSUE TITLE
Masonry bug on hidden elements on page load

### ISSUE THREAD

**Issue by ivanhalen** [desandro/masonry#665] opened 2015-02-19 17:18 UTC
Hello, I have a problem with Masonry (and Isotope): when elements are hidden on page load (i.e in a Bootstrap dropdown mega menu) they overlap; overlap is gone resizing the page, or showing elements on page load (i.e using the class "open" to trigger the opened mega menu)

Here are some fiddles (with Isotope, but it's the same with Masonry):
Bug: http://jsfiddle.net/z4jugbks/1/
Opened menu (bug gone): http://jsfiddle.net/nj01uoay/3/

Am I missing something? Please, any help?
Thank you :-)

**Comment by desandro** [comment] 2015-02-20 14:07
This sounds like a duplicate of #217

---

The content in the hidden tabs is hidden, therefore Masonry cannot properly measure the items for layout.

Possible solutions:

+ trigger `.masonry()` on all content before you set up the tabs.
+ trigger `.masonry()` on selected content when that tab is selected.

For your example, you can trigger layout after the dropdown menu is clicked.  See http://jsfiddle.net/z4jugbks/3/

``` js
$('.dropdown-toggle').on( 'click', function() {
    // do async to allow menu to open
    setTimeout( function() {
        $container.isotope('layout');
    });
});
```

**Closed by desandro** 2015-02-20 14:07 UTC
