### ISSUE TITLE
reloadItems() loses isTransitioning state on items

### ISSUE THREAD

**Issue by IlyaSemenov** [desandro/masonry#498] opened 2014-02-05 18:31 UTC
Problem: reloadItems() actually reloads all items from scratch and thus loses item.isTransitioning flags. If you invoke reloadItems() when there's an item which has _just_ begun to move, and invoke relayout() which is supposed to put that item back, that will not work as expected (the item will be considered "not moved and not in transition", thus skipped).

I created a jsfiddle to demonstrate the problem:
http://jsfiddle.net/semenov/qT936/

Possible solutions:
a) Implement proper merging on masonry.items, that is: do not recreate an Item if its element has already been in previous masonry.items, only create Item objects for new DOM elements.
b) Teach _itemize() to recognize transitioning elements by looking onto translate property.
c) Store item.isTransitioning flag as a custom data attribute on items DOM elements, and change itemize() to pull that data.

**Comment by wilsonsergio2500** [comment] 2015-02-20 23:14
Got this problem of transition still being true, the odd thing is that when i debug with IE i see ontransitionend firing the right way, and the transforms properties get removed. It is not the case for Chrome though.  
I am using the angularjs version of masonry, everything renders well the issue is that if the transform class is not removed it has further css consequences in the display :-(

**Comment by vinh0604** [comment] 2015-10-01 08:06
Hi, is there any updates on it? I'm facing this when using `angular-masonry` too, my problem is that every time user type something into search box, the layout will be changed and causing problem with items in transition.

**Comment by desandro** [comment] 2017-04-20 17:56
This issue has been quiet for a while. Closing as `wontfix`.

**Closed by desandro** 2017-04-20 17:56 UTC
Labels: bug
