### ISSUE TITLE
Safari Overlapping Items - Masonry and Infinite Scroll

### ISSUE THREAD

**Issue by josefarrugia** [desandro/masonry#976] opened 2017-07-25 22:33 UTC
Hey there,

I have been scratching my head on this for hours now. It works beautifully and gorgeously on Chrome. Kudos to you @desandro! Strangely, Safari doesn't seem to be playing fairly. The items and images are overlapping each other. I am using it with Infinite Scroll. Here's my code:

``` js
$(function() {

var $grid = $('.grid').masonry({
  itemSelector: '.grid-item',
	hiddenStyle: { opacity: 0 }
});

var msnry = $grid.data('masonry');


	$grid.infiniteScroll({
	  path: function() {
	    var pageNumber = ( this.loadCount + 1 ) * 6;
	    return '/site/beta/P' + pageNumber;
	  },
	  append: '.grid-item',
	  outlayer: msnry,
	  history: false,
		checkLastPage: '.newer'
	},

	function( newElements ) {
		var $newElems = $( newElements ).hide();
		$newElems.imagesLoaded(function(){
			$grid.masonry( 'appended', $newElems );
		});
	}
	);
});
```

I hope someone could guide me in the right direction :-)

**Comment by desandro** [comment] 2017-07-27 19:36
Duplicate of metafizzy/infinite-scroll#671

Follow there for progress. 

Also, you can remove the callback code now that you're using Infinite Scroll v3. 

``` js
$(function() {

  var $grid = $('.grid').masonry({
    itemSelector: '.grid-item',
  });

  var msnry = $grid.data('masonry');

  $grid.infiniteScroll({
    path: function() {
      var pageNumber = ( this.loadCount + 1 ) * 6;
      return '/site/beta/P' + pageNumber;
    },
    append: '.grid-item',
    outlayer: msnry,
    history: false,
    checkLastPage: '.newer'
  });

});
```

**Comment by TaktakTaktouk** [comment] 2017-07-28 13:11
Can you fix your example on codepen please?
https://codepen.io/desandro/pen/eRRQVo

**Comment by desandro** [comment] 2017-07-28 18:22
@TaktakTaktouk That's a separate issue as that example loads other CodePen URLs

**Comment by TaktakTaktouk** [comment] 2017-07-28 22:04
So How can I do to fixe the issue with safari because I use the same example in my website?

**Closed** 2018-03-15 01:48 UTC
