### ISSUE TITLE
Loading items when the container div (Masonary element) is hidden

### ISSUE THREAD

**Issue by QaisarRajput** [desandro/masonry#729] opened 2015-07-26 14:44 UTC
if my container div is hidden (as in the case of Tabs) and i load items in an Ajax response , Masonary loads the items but do not adjust them as it should...

But if i try it when the div is shown at the moment i load items (simple div without Tabs) . it works fine 

Tried "layout" and "reloadItems" but did'nt work..

**Comment by desandro** [comment] 2015-07-27 17:34
The content in the hidden tabs is hidden, therefore Masonry cannot properly measure the items for layout.

Possible solutions:

+ trigger `.masonry()` before you set up the tabs.
+ trigger `.masonry()` on related content when that tab is selected.

---

Duplicate of #217

**Closed by desandro** 2015-07-27 17:34 UTC

**Comment by zenPidgin** [comment] 2015-07-27 21:15
Would setting the visibility in css work? The box would still be there to be measured, but would not show on the screen.
http://www.w3schools.com/cssref/pr_class_visibility.asp
