### ISSUE TITLE
masonry is applied to elements that are not defined in the options

### ISSUE THREAD

**Issue by timholz** [desandro/masonry#1027] opened 2018-01-11 17:49 UTC
Hi - i use masonry on a wordpress site. All works well. But masonry adds inline style to widgets in the footer that i did not define in the options. I tried to remove the inline style with jquery and also tried to prevent the layout on these elements, no luck.
Ever heard of such a thing?
I am aware that you prefer a code pen, but it is rather difficult to mimic this issue.
regards
theo

**Comment by timholz** [comment] 2018-01-11 19:32
Hi - i found a workaround. It's not enough to just set initLayout to false. It is also necessary to remove all inline styles on resize. Then masonry can pe prevented. But still, it is strange that this happens to elements that are not defined.

`$(window).on('resize', function () {
    $('.flexible-widget-area').masonry({
  initLayout: false,
});
    $(".site-footer .flexible-widget-area, .site-footer .flexible-widget-area aside").removeAttr("style");
});`

regards
theo

**Comment by desandro** [comment] 2018-01-12 15:37
Let's keep discussion to one issue. Closing as a duplicate of #1026

**Closed** 2018-01-14 13:59 UTC
Labels: duplicate
