### ISSUE TITLE
Problem swapping item sets in masonry

### ISSUE THREAD

**Issue by m-a-wilson** [desandro/masonry#745] opened 2015-08-21 17:59 UTC
I am attempting to swap out a the items in a masonry element. Actually that part works for one (IE10) or two (FireFox) swaps. Subsequent swaps result in the left positions of the items being set to zero or some other invalid value. Note that the target app retrieves sets of items via RESTful requests.

I have tried putting `$('.jobs').masonry();` and `$('.jobs').masonry('layout');` after the `remove` with the only notable result that the left positions are set to zero exclusively.

See this CODEPEN: http://codepen.io/anon/pen/YXoJRN

**Comment by m-a-wilson** [comment] 2015-08-21 18:16
NOTE: resizing the browser window by any amount corrects the left positions.

**Comment by desandro** [comment] 2015-12-06 16:35
Thanks for reporting this bug. This looks to be a duplicate of #678

**Closed by desandro** 2015-12-06 16:35 UTC
