### ISSUE TITLE
Space available for 3 columns but it breaks

### ISSUE THREAD

**Issue by thehung2224** [desandro/masonry#786] opened 2015-11-18 10:01 UTC
In the example I have 3 columns with each 33.33% width. Container is 1170px (Bootstrap) but masonry only displays 2 columns and breaks the third one down.

Demo: http://codepen.io/thehung1724/pen/ojVzYo

**Comment by desandro** [comment] 2015-11-18 13:55
Closing as a duplicate of metafizzy/isotope#1006

**Closed by desandro** 2015-11-18 13:55 UTC
