### ISSUE TITLE
Images are overlapping in chrome/safari

### ISSUE THREAD

**Issue by imran031387** [desandro/masonry#684] opened 2015-04-03 17:29 UTC
Hi,
i have used masonry for display contents with images and it's working fine in Firefox but in chrome/safari (if i resize the window it's working ) it's overlapping any idea why? i have googled  regarding this issue and i find various answers none of that didn't work for me 
Following are the solutions i tried
1.setting the height and width for img
2.loading the script in onload function
3.used the imageloader

Thanks

**Comment by desandro** [comment] 2015-04-03 17:37
Might it be a problem with web fonts? See http://masonry.desandro.com/faq.html#overlapping

I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by romaricdrigon** [comment] 2015-05-05 08:44
Hi,
Same issue here: I have a layout with a bunch of fixed-size divs aligned. At first everything is good, but eventually when I scroll I will end up with the 2 last images overlapping.
The 2 images from the last line (the only ones on that line) don't have their position calculated correctly.

The issue is only with Chrome, Firefox is fine.
I'll try to give you a Codepen, but maybe it is some issue implying InfiniteScroll too so I'm not sure I'll succeed.

**Comment by romaricdrigon** [comment] 2015-05-05 09:22
Ok so on my side it's now fixed: it was indeed an image loading issue.
Weird thing, it was not happening for the initial page content, but when more data was fetched during scroll it was failing every time.
Using imagesLoaded plugin solved the issue. 
Thanks again for Masonry!

**Closed** 2015-05-08 12:27 UTC
Labels: test case required
